apiVersion: cache.gcp.crossplane.io/v1beta1
kind: CloudMemorystoreInstance
metadata:
  name: cymbal-memstore
  namespace: default
spec:
  providerConfigRef:
    name: gcp-config
  forProvider:
    memorySizeGb: 2
    region: us-central1
    tier: BASIC
