apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: cymbal-bucket
  namespace: default
spec:
  providerConfigRef:
    name: aws-config
  forProvider:
    locationConstraint: us-east-1
    acl: private
