apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: redisrequireversion
spec:
  crd:
    spec:
      names:
        kind: RedisRequireVersion
      validation:
        openAPIV3Schema:
          properties:
            allowedName:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package redisrequireversion
        violation[{"msg": msg}] {
          input.review.object.kind == "RedisInstance"
          input.review.object.spec.redisVersion != input.parameters.allowedVersion
          msg := sprintf("Redis Version %v is not allowed, must use version: %v", [input.review.object.spec.redisVersion, input.parameters.allowedVersion])
        }
