apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-sample
  namespace: config-connector-resources
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cymbal-gsa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:yaml-your-cloud.svc.id.goog[cymbal-shops/cymbal-ksa]
